# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
title:              "Liau Jian Jie"

# SEO
description:        "builder, coder & designer"
url:                "//jianjie.co"
author:             "liaujianjie"
twitter:
  username:         "liaujianjie"

# Google Analytics
googleAnalytics:
  trackingId:       "UA-53668266-3"

# Contact
facebook:           "liaujianjie"
github:             "liaujianjie"
email:              "hello@jianjie.co"
linkedin:           "liaujianjie"

# URL
#baseurl:            "//jianjie.co"
#permalink:          /:collection/:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "/"
  - name:           "Works"
    href:           "/works/"
  # - name:           "Blog"
  #   href:           "/blog/"
  - name:           "Contact"
    href:           "/contact/"
  - name:           "Resume"
    href:           "/resume/"

# Sass
sass:
  style:            :compressed

# Collections
collections:
  works:
    output: true
    permalink: /:collection/:title
  blog:
    output: true
    permalink: /:collection/:year/:month/:day/:title/
  includes:
    output: false

# Scopes
defaults:

  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         "_blog"
      type:         "blog"
    values:
      layout:       "post"
  -
    scope:
      path:         "_works"
      type:         "work"
    values:
      layout:       "work"
  -
    scope:
      path:         "_includes"
      type:         "includes"
    values:
      layout:       "include"

gems:
  - jekyll-seo-tag
  - jekyll-gist
