# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Liau Jian Jie"
subtitle:           "builder, coder & designer"

# Contact
twitter:            "jianjie_"
email:              "hello@jianjie.co"

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
#permalink:          /:collection/:year/:month/:day/:title/

# Markdown
markdown:           kramdown
kramdown:           
  parse_block_html: true

# Navigation
nav:
  - name:           "About"
    href:           "/"
#  - name:           "Works"
#    href:           "/works/"
  - name:           "Blog"
    href:           "/blog/"

# Sass
sass:
  style:            :compressed
  
# Collections
collections:
  works:
    output: true
    permalink: /:collection/:title
  blog:
    output: true
    permalink: /:collection/:year/:month/:day/:title/
  includes:
    output: false

# Scopes
defaults:

  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         "_blog"
      type:         "blog"
    values:
      layout:       "post"
  -
    scope:
      path:         "_works"
      type:         "work"
    values:
      layout:       "work"
  -
    scope:
      path:         "_includes"
      type:         "includes"
    values:
      layout:       "include"
